# Generated by Django 4.1.3 on 2022-11-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='curso',
        ),
    ]
