# Generated by Django 4.1.3 on 2022-11-19 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_remove_alumnos_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.cursos'),
        ),
    ]
