# Generated by Django 4.1.3 on 2022-12-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_inasistencias_tarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
