# Generated by Django 4.1.3 on 2022-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_inasistencias_tarde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
