# Generated by Django 4.1.3 on 2022-12-30 05:20

import alumnos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnos', '0009_alter_alumnos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='user',
            field=models.OneToOneField(blank=True, default=alumnos.models.Alumnos.generarUsuario, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
