# Generated by Django 4.1.3 on 2022-12-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_alter_alumnos_foto_alter_alumnos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='foto',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
