# Generated by Django 4.1.3 on 2022-12-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0012_alumnos_archivo_alter_alumnos_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='foto',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos.AlumnosPicture/bytes/filename/mimetype'),
        ),
    ]
