# Generated by Django 4.1.3 on 2023-01-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0013_alumnospicture_remove_alumnos_archivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnospicture',
            old_name='bytes',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos.AlumnosPicture/name/mimetype/filename'),
        ),
    ]
