# Generated by Django 4.1.3 on 2023-01-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0014_rename_bytes_alumnospicture_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnospicture',
            old_name='name',
            new_name='bytes',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos.AlumnosPicture/bytes/mimetype/filename'),
        ),
    ]
