# Generated by Django 4.1.3 on 2023-01-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0017_alumnos_binario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='binario',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
