# Generated by Django 4.1.3 on 2023-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0018_alter_alumnos_binario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
