# Generated by Django 4.1.3 on 2023-01-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0020_alter_alumnos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
